### PR TITLE
initialize code base

### PR DESCRIPTION
**Pull request by libenchao**
Initialize code base.
1, Add ```NameNode```, ```DataNode``` 
2, Add ```target``` to ```gitignore``` file.

# Reviewers
- [ ] @yanyiping 
- [ ] @songpengwei

### CODE REVIEW

**Comment by libenchao** [comment]
@songpengwei @yanyiping guys, if you do not post any suggestions, I will merge this tonight.

**Comment by songpengwei** [comment]
1. I think the package name can be a word without underline and be more short. For example, org.yls.tdfs
2. Is it better that the namenode.java and datanode.java are placed in individual package or folder?

**Comment by songpengwei** [comment]
1. the package name could be words more short without underline, for example, org.yls.tdfs
2. Is it better to put the namenode.java and datanode.java to individual package? Then it is easier for us to extend  in the future.
   @libenchao @yanyiping

**Comment by libenchao** [comment]
@songpengwei 
1, good idea. I hate `three_idiots` too. But I don't think `yls` is good organization name, imagine that `www.yls.org`. Any other good ideas?
2, for now, I think it's ok to put these two class in same package, as `HDFS` do.

**Comment by songpengwei** [comment]
1. how about  tridiot(three idiots) ? crazylab? @libenchao

**Comment by libenchao** [comment]
@songpengwei I love `tridiot`, it's great! What do you think? @yanyiping

**Comment by songpengwei** [comment]
dashen is off line~ hahaha
and the package name can be 
org.tridiot.tdfs 
the code now does not include tdfs~

**Comment by songpengwei** [comment]
@libenchao

**Comment by libenchao** [comment]
yes, good idea.

**Comment by libenchao** [comment]
ps: you do not need to `@` each time. all `participants` will get notified automatically.

image

**Comment by libenchao** [comment]
@songpengwei @yanyiping codes updated.

**Pull request merged**
